# Generated by Django 5.2.3 on 2025-06-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
